spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 本番は "validate" や "none" 推奨
    show-sql: true      # SQLをコンソールに表示
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # JPAが生成するSQLを指定（今回はPostgreSQL）
        "[hibernate:format_sql]": true                    # SQLを整形して表示（デバッグ時にSQLを見やすくするため）
        "[use_sql_comments]": true                        # SQLにコメントを追加（どの部分でエラーが発生したのかが分かる）
        "[hibernate.id.new_generator_mappings]": true     # 有効にしないと古いID生成方式が使われることがある